import { User, UserRole } from 'users/entities/user.entity';

export const dummyUsers: User[] = [
  {
    id: 1,
    name: 'Zehra Duran',
    email: 'zehra.duran@example.com',
    password: 'Rh(E`5^i)u',
    isActive: true,
    role: UserRole.USER,
    birthdate: '1995-05-05',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 2,
    name: 'Abid İnönü',
    email: 'abid.i̇nönü@example.com',
    password: 'Jt:@{:p3bu',
    isActive: true,
    role: UserRole.USER,
    birthdate: '2003-08-25',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 3,
    name: 'Aykut Zengin',
    email: 'aykut.zengin@example.com',
    password: 'W[>M!*w@"4',
    isActive: true,
    role: UserRole.USER,
    birthdate: '2004-07-28',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 4,
    name: 'Sayın Sezgin',
    email: 'sayın.sezgin@example.com',
    password: 'nDV9H#ByAy',
    isActive: true,
    role: UserRole.USER,
    birthdate: '1992-07-11',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 5,
    name: 'Temime Korutürk',
    email: 'temime.korutürk@example.com',
    password: '?^0zUg4fY@',
    isActive: false,
    role: UserRole.USER,
    birthdate: '1986-01-31',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 6,
    name: 'Nafii Zorlu',
    email: 'nafii.zorlu@example.com',
    password: '6YBB+l^f4W',
    isActive: true,
    role: UserRole.USER,
    birthdate: '1985-07-12',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 7,
    name: 'Ünal Şensoy',
    email: 'ünal.şensoy@example.com',
    password: ':3Br18XADo',
    isActive: true,
    role: UserRole.USER,
    birthdate: '1994-01-15',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 8,
    name: 'Hasgül Çorlu',
    email: 'hasgül.çorlu@example.com',
    password: 'v4LyT[*H6V',
    isActive: true,
    role: UserRole.USER,
    birthdate: '2005-01-31',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 9,
    name: 'Kefser Akar',
    email: 'kefser.akar@example.com',
    password: "D;F2(P[7n'",
    isActive: true,
    role: UserRole.USER,
    birthdate: '1989-01-02',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 10,
    name: 'Aliihsan Korutürk',
    email: 'aliihsan.korutürk@example.com',
    password: 'U2;Pr,h~/6',
    isActive: true,
    role: UserRole.USER,
    birthdate: '1985-09-26',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 11,
    name: 'Sadiye Demir',
    email: 'sadiye.demir@example.com',
    password: '8,#NFW(#]n',
    isActive: true,
    role: UserRole.USER,
    birthdate: '2005-09-22',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 12,
    name: 'Şahat Bilgin',
    email: 'şahat.bilgin@example.com',
    password: 'fyxmnkX-5;',
    isActive: true,
    role: UserRole.USER,
    birthdate: '1996-12-19',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 13,
    name: 'Şüküfe Sakarya',
    email: 'şüküfe.sakarya@example.com',
    password: 'u<XI8zEuK3',
    isActive: true,
    role: UserRole.ADMIN,
    birthdate: '1993-11-07',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 14,
    name: 'Gümüştekin Sezer',
    email: 'gümüştekin.sezer@example.com',
    password: ')i7UZIf[oG',
    isActive: true,
    role: UserRole.USER,
    birthdate: '2003-09-22',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 15,
    name: 'Cindoruk Bilir',
    email: 'cindoruk.bilir@example.com',
    password: '88#O`i+c_0',
    isActive: true,
    role: UserRole.ADMIN,
    birthdate: '1986-09-11',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 16,
    name: 'Muhammet Yaman',
    email: 'muhammet.yaman@example.com',
    password: '+sG_sV1oHy',
    isActive: true,
    role: UserRole.SUPER_ADMIN,
    birthdate: '1989-10-14',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 17,
    name: 'Satrettin Yüksel',
    email: 'satrettin.yüksel@example.com',
    password: 'tBT6>~6o)|',
    isActive: true,
    role: UserRole.USER,
    birthdate: '1989-01-09',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 18,
    name: 'Mübetcel Şafak',
    email: 'mübetcel.şafak@example.com',
    password: '>FX,fR2<+V',
    isActive: true,
    role: UserRole.USER,
    birthdate: '2005-07-26',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 19,
    name: 'Andiç Yıldırım',
    email: 'andiç.yıldırım@example.com',
    password: '!HY;Sc|lU2',
    isActive: false,
    role: UserRole.USER,
    birthdate: '1996-12-16',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
  {
    id: 20,
    name: 'Nazlihan Yıldırım',
    email: 'nazlihan.yıldırım@example.com',
    password: '*8s2x#<YGC',
    isActive: true,
    role: UserRole.USER,
    birthdate: '1997-06-28',
    createdAt: new Date('1995-05-05'),
    updatedAt: new Date('1995-05-05'),
  },
];
